// Generated by packages/kiwicaptcha/tools/sync-brand.mjs. Do not edit.
export const KIWI_MARK_PATHS = [
  "M32 42 C32 35 43 35 43 42 C43 51 29 54 23 46 C16 36 25 28 35 29 C47 29 54 38 53 46 C52 56 43 60 31 59 C17 58 9 51 10 41 C10 33 16 28 21 28",
  "M22 25 V16 A10 10 0 0 1 42 16 V25"
] as const;
