#!/usr/bin/env node
/**
 * ledger.mjs — the runs ledger aggregator and the output generator.
 *
 * Reads every run document the orchestrator wrote under
 * engine/runs/<ts>-<campaign>-seed<seed>.json, keeps the latest run
 * per campaign, and generates the two Part 10.4 outputs:
 *
 *   THREATS.md            the living table at the repo root: attack
 *                         class, current economic result, status,
 *   docs/cost-to-abuse.md the public per-value-class cost table from
 *                         the bench reference costs and the fresh
 *                         measurement the campaigns recorded.
 *
 * Both files are generated: the header marks them as engine output,
 * the engine version is the seed, and regeneration is idempotent.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ENGINE_DIR = dirname(fileURLToPath(import.meta.url));
const RT_DIR = dirname(ENGINE_DIR);
const REPO = dirname(dirname(RT_DIR));
const RUNS_DIR = join(ENGINE_DIR, "runs");

const seedArg = process.argv.includes("--seed")
    ? process.argv[process.argv.indexOf("--seed") + 1]
    : (process.env.KIWI_RT_SEED ?? "0x6b776d74");

// ---------- the runs ledger ----------
const byCampaign = new Map();
for (const name of readdirSync(RUNS_DIR).filter((f) => f.endsWith(".json")).sort()) {
    try {
        const run = JSON.parse(readFileSync(join(RUNS_DIR, name), "utf8"));
        if (!run.campaign) continue;
        byCampaign.set(run.campaign, run);
    } catch {
        // an unreadable run document is skipped, never fatal
    }
}
const latest = [...byCampaign.values()].sort((a, b) => a.campaign.localeCompare(b.campaign));

function statusOf(run) {
    if (!run) return { status: "NO-DATA", verdict: "never run in this ledger" };
    return run.result === "PASS"
        ? { status: "GREEN", verdict: run.economic ?? "attacker uneconomic" }
        : { status: "RED", verdict: run.detail ?? "see run document" };
}

const threatRows = latest.map((run) => {
    const { status, verdict } = statusOf(run);
    return `| ${run.attackClass ?? run.campaign} | ${verdict} | ${status} |`;
});

const threats = `# THREATS

The living output of the automated red-team engine (change.md Part 10).
Generated from the runs ledger by \`tools/redteam/engine/ledger.mjs\`;
regenerate with the orchestrator. Status GREEN means the campaign's
required result held on the current repo state, RED means it did not,
NO-DATA means the campaign has not run into this ledger yet.

Seed: \`${seedArg}\` · Ledger entries: ${latest.length}

| Attack class | Current economic result | Status |
| --- | --- | --- |
${threatRows.join("\n")}

## The bounds the engine holds itself to

- Every campaign states its environment downscale openly.
- Every finding is reproduced deterministically before it gates.
- Every committed repro is a reviewable test under tools/redteam/findings/.
- The engine targets loopback and private addresses only.
`;

writeFileSync(join(REPO, "THREATS.md"), threats);

// ---------- the cost-to-abuse table ----------
let reference = {};
try {
    const raw = JSON.parse(readFileSync(
        join(REPO, "packages/kiwicaptcha-solver/reference-costs.json"), "utf8"));
    reference = raw;
} catch {
    // without the reference table the doc degrades to the measured row
}
const asOf = reference.provenance?.as_of ?? "unrecorded";
const rateRows = (reference.attacker_rates ?? [])
    .map((rate) => `| ${rate.hardware_class} | ${rate.hashes_per_second.toExponential(1)} hashes/s | sha256 | ${rate.id} |`);

const measured = latest
    .map((run) => run.metrics?.sha16_solve_us)
    .filter((v) => typeof v === "number" && v > 0);
const sha16Us = measured.at(-1);

const solveCostRows = [];
if (sha16Us) {
    solveCostRows.push(
        `| sha16 (browser rung) | ${Math.round(sha16Us).toLocaleString("en-US")} us per solve (measured on the campaign bench) | native sha256, single core |`,
    );
}
solveCostRows.push(
    "| sha18 | ~4x the sha16 row (16x work, minus find cost) | native sha256, single core |",
    "| sha20 | ~16x the sha16 row | native sha256, single core |",
    "| argon16..64 | memory-hard; see the bench's own table | native argon2id, single core |",
    "| rsw | inherently sequential; no hardware class buys a parallel speedup | time-lock squaring |",
);

const costDoc = `# Cost to abuse

The public per-value-class table (change.md Part 10.4): what an
attacker pays per successful abuse per value class, measured and
published rather than asserted. Generated by the red-team engine's
ledger from the bench reference costs and the campaigns' fresh
measurements on the release machine.

Reference class provenance: ${reference.provenance?.statement ?? "see reference-costs.json"}
(as of ${asOf}; refreshed by hand, stale entries replaced).

## Hardware classes the attacker rents

| Hardware class | Advertised rate | Algorithm | Class id |
| --- | --- | --- | --- |
${rateRows.join("\n")}

## What one solve costs an attacker here

| Ladder rung | Measured cost | Note |
| --- | --- | --- |
${solveCostRows.join("\n")}

## Reading the table

The campaigns report cost per ACCEPTED abuse. Every green campaign in
THREATS.md is a zero-acceptance run, so the attacker's cost per
successful abuse is unbounded there: the spend is real (the bench
prices every solve) and the yield is zero. The engine's economic
lines carry the measured spend per honest solve; the bench's own
verdict per value class (packages/kiwicaptcha-solver bench) prices
each scope's abuse value against these rates.

${reference.provenance?.honesty ?? ""}
`;

const costPath = join(REPO, "docs/cost-to-abuse.md");
writeFileSync(costPath, costDoc);

console.log(`ledger: ${latest.length} campaigns aggregated; THREATS.md and docs/cost-to-abuse.md generated`);
